point_cloud_topic: "/camera/depth/color/points"
map_frame_id: "odom"
sensor_frame_id: "ground_camera_depth_optical_frame"
robot_base_frame_id: "base"
robot_pose_with_covariance_topic: "/vilens/pose_optimized"
robot_pose_cache_size: 500
track_point_frame_id: "base"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0


# Robot.

min_update_rate: 0.5
time_tolerance: 0.5
time_offset_for_point_cloud: 0.0
sensor_processor/ignore_points_above: 0.4
robot_motion_map_update/covariance_scale: 0.01

# Map.
length_in_x: 10.0
length_in_y: 4.0
position_x: 0.0
position_y: 0.0
resolution: 0.02
min_variance: 0.0001
max_variance: 0.05
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.001
surface_normal_positive_axis: z
fused_map_publishing_rate: 0.5
enable_visibility_cleanup: false
visibility_cleanup_rate: 1.0
scanning_duration: 1.0
